import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Stack from 'react-bootstrap/Stack';
import CustomNavbar from '../components/CustomNavbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>NatureDAO - Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>

      <Container className={styles.main_window} fluid>
        <Row className={styles.rows}>
          <CustomNavbar />
          <Col className={styles.cols}>1</Col>
          <Col className={styles.cols}>2</Col>
          <Col className={styles.cols}>3</Col>
        </Row>
        <Row className={styles.rows}>
          <Col className={styles.cols}>4</Col>
          <Col className={styles.cols}>5</Col>
          <Col className={styles.cols}>6</Col>
        </Row>
        <Row className={styles.rows}>
          <Col className={styles.cols}>7</Col>
          <Col className={styles.cols}>8</Col>
          <Col className={styles.cols}>9</Col>
        </Row>
      </Container>
    </>
  );
}
